/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import ckeditor5 from "@_sh/strapi-plugin-ckeditor/strapi-admin";
import dragDropContentTypes from "@retikolo/drag-drop-content-types/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import meilisearch from "strapi-plugin-meilisearch/strapi-admin";
import previewButton from "strapi-plugin-preview-button/strapi-admin";
import redirects from "strapi-plugin-redirects/strapi-admin";
import sitemap from "strapi-plugin-sitemap/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    ckeditor5: ckeditor5,
    "drag-drop-content-types": dragDropContentTypes,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    meilisearch: meilisearch,
    "preview-button": previewButton,
    redirects: redirects,
    sitemap: sitemap,
  },
});
